# Generated by Django 4.2.3 on 2023-07-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theWowAdv', '0003_rename_responseadvertisement_response_advert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Принято'),
        ),
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.TextField(max_length=512, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='response',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок'),
        ),
    ]
