# Generated by Django 4.2.3 on 2023-07-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theWowAdv', '0006_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(choices=[('T', 'Танки'), ('HM', 'Хилы'), ('DD', 'ДД'), ('TrM', 'Торговцы'), ('GM', 'Гилдмастеры'), ('QG', 'Квестгиверы'), ('FM', 'Кузнецы'), ('LM', 'Кожевники'), ('PM', 'Зельевары'), ('WM', 'Мастера заклинаний')], default='T', max_length=3, verbose_name='Категория'),
        ),
    ]
