# Generated by Django 4.2.3 on 2023-07-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theWowAdv', '0008_alter_subscription_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterSubscribedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
        ),
    ]
