# Generated by Django 4.2.3 on 2023-07-27 12:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theWowAdv', '0009_newslettersubscribedusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='CategorySubscription',
        ),
    ]
