# Generated by Django 4.2.3 on 2023-07-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theWowAdv', '0010_rename_subscription_categorysubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorysubscription',
            options={'verbose_name': 'Подписки по категориям', 'verbose_name_plural': 'Подписки по категориям'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscribedusers',
            options={'verbose_name': 'Новостная подписка', 'verbose_name_plural': 'Новостные подписки'},
        ),
    ]
